name: opencode
services:
  opencode:
    image: lietxia/opencode:latest
    # build: .
    container_name: opencode-webui
    ports:
      - 4096:4096
      - 9999:9999
      - 8888:8888
    environment:
      OPENCODE_SERVER_USERNAME: ubuntu
      OPENCODE_SERVER_PASSWORD: ubuntu
      OPENCODE_PORT: 4096
      OPENCODE_HOSTNAME: 0.0.0.0
    volumes:
      - ./workspace/:/workspace/
    restart: unless-stopped

  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    ports:
      - 10086:80
    volumes:
      - ./workspace/:/srv/
    restart: unless-stopped